# Configuración para DiscordIntegrator

# Token del bot de Discord
discord-token: "TU_TOKEN_DEL_BOT"

# ID del canal de Discord para el chat cruzado (mensajes generales)
discord-chat-channel-id: "ID_DEL_CANAL_CHAT"

# ID del canal de Discord para eventos (muertes, asesinatos, logros)
discord-events-channel-id: "ID_DEL_CANAL_EVENTOS"
